<?php

function highlighted_annos_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if($form['#id'] == 'views-exposed-form-annosidebar-annosidebar'){// views-exposed-form-annosidebar-annosidebar for block view; views-exposed-form-annosidebar-page-1 for page view
    $form['nid'] = array(
    '#type' => 'hidden', 
     '#attributes' => array(
        'id'=>'edit-nid--2',  //edit-nid--2 for block view; edit-nid for page view
      ),
    );
  }
}

function highlighted_annos_views_query_alter(&$view, &$query) {
  if ($view->current_display == 'annosidebar' && $view->exposed_raw_input['nid']) {
    // first we grab the value from our filter and convert it into an array
    // make sure you use the same character you used to delimit the string
    //echo $view->exposed_raw_input['nid']; shows NIDs received in correct x,y format
    $nids = explode(',',$view->exposed_raw_input['nid']);
    // we loop over the array of values we created from our exposed filter field
    foreach ($nids as $nid){
      // Previously included empty brackets [] after ['conditions'] for if you want to append the new conditions instead of overwriting them. 
      $query->where[1]['conditions'][] = array(
        'field' => 'node.nid',
        'value' => $nid,
        'operator' => '=',  // condition operator. I want to filter to matching NIDs so I'm using equal = here eventually + setting the Views UI filter to equals.
      );
    }
  }
}

/**
 * Implements hook_views_pre_build() to fix .submit redirecting to another page
 */
function highlighted_annos_views_pre_build(&$view) {
  if ($view->name == 'annosidebar') {
    // Set the override path to the current page. This will redirect the back view to the current page when submitted in case AJAX fails.
    $view->override_path = $_GET['q'];
  }
}